[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    [".tmux/plugins/tpm".pull]
        args = ["--depth", "1"]
    [".tmux/plugins/tpm".clone]
        args = ["--depth", "1"]