[".config/liquidprompt"]
    type = "git-repo"
    url = "https://github.com/nojhan/liquidprompt.git"
    [".config/liquidprompt".pull]
        args = ["--depth", "1"]
    [".config/liquidprompt".clone]
     args = ["--depth", "1"]