# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the blank line at the start of the prompt
add_newline = false

format = '$time $sudo\[$hostname:$directory\] $git_branch$git_metrics$git_status$status$cmd_duration$character'

[cmd_duration]
format = '[$duration](bold yellow)'

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncate_to_repo = false

[git_branch]
format = '[$branch(:$remote_branch)]($style)'

[git_commit]
format = '[($hash$tag)]($style)'
disabled = true

[git_metrics]
format = '((\([+$added]($added_style))(/[-$deleted]($deleted_style))\))'
disabled = false

[git_status]
format = "$ahead_behind$staged"

[hostname]
ssh_symbol = "🌐"
format = '[$ssh_symbol](bold blue)[$hostname]($style)'

[status]
disabled = false

[sudo]
disabled = false

[time]
format = '[$time]($style)'
style = 'blue'
disabled = false
